export const stateSelectOptions = [
    'Alaska',
    'American Samoa',
    'Arkansas',
    'California',
    'Colorado',
    'District Of Columbia',
    'Federated States Of Micronesia',
    'Georgia',
    'Guam',
    'Idaho',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Marshall Islands',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New York',
    'Northern Mariana Islands',
    'Ohio',
    'South Carolina',
    'Texas',
    'Virginia',
    'Wyoming',
]